name: CI Pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code base
        run: |
          pip install poetry
          poetry install
          poetry run flake8

  docker-build:
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local test)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: local-test-image:latest

  docker-deploy:
    name: Push to DockerHub
    needs: [run-lint, docker-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project:${{ github.sha }}
