name: Complete CI/CD Pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  # CI JOB - Continuous Integration
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
          
      - name: Lint with flake8
        run: |
          
          
      - name: Run tests
        run: |
         

  # BUILD JOB - Build Docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image (test build)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: test-image:latest

  # CD JOB - Continuous Deployment (само на main branch)
  deploy:
    needs: [test-and-lint, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project:${{ github.sha }}
